### PR TITLE
Fix docker release job

### PR DESCRIPTION
**Pull request by timvisee**
Our Docker release job on CI is broken. It fails near the end: https://github.com/qdrant/qdrant/actions/runs/6161250399/job/16730823202

A `pull` step was missing near the bottom. Therefore the `-unprivileged` image was never pushed to [GitHub packages](https://github.com/qdrant/qdrant/pkgs/container/qdrant%2Fqdrant). This command has now been added.

I've also restructured the job a bit to clarify what is happening. I found it super confusing before.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Review by agourlay — APPROVED** [review]
Thank you for the comments, it is indeed pretty confusing :+1:

**Review by ffuugoo — APPROVED** [review]
LGTM 👌

**Comment by agourlay** [comment]
Maybe we need to update the release notes to remove the mention of the unprivileged image if we failed to push it?
https://github.com/qdrant/qdrant/releases/tag/v1.5.1

**Comment by timvisee** [comment]
> Maybe we need to update the release notes to remove the mention of the unprivileged image if we failed to push it? https://github.com/qdrant/qdrant/releases/tag/v1.5.1

Good that you point this out.

They are pushed to Docker Hub, just not to GitHub packages.

I can try to push this manually.

**Comment by timvisee** [comment]
Done!

image

**Pull request merged**
