### PR TITLE
add openapi validation during generation #208

### PR DESCRIPTION
**Pull request by generall**
- add `redocly/openapi-cli lint` as a part of schema generation pipeline
- fix redocly warnings

### CODE REVIEW

**Review by agourlay — APPROVED** [review]
Nice :+1:

**Comment by agourlay** [comment]
Benchmarking locally I realized that I forgot to update the file `benches/service/collection_stress.js`

```
diff --git a/benches/service/collection_stress.js b/benches/service/collection_stress.js
index 1ed9679..7a58f71 100644
--- a/benches/service/collection_stress.js
+++ b/benches/service/collection_stress.js
@@ -110,12 +110,10 @@ export function setup() {
 }
 
 export default function () {
-    var url = `${host}/collections/${collection_name}`;
+    var url = `${host}/collections/${collection_name}/points`;
 
     var payload = JSON.stringify({
-        "upsert_points": {
-            "points": Array.from({ length: vectors_per_batch }, () => generate_point()),
-        }
+        "points": Array.from({ length: vectors_per_batch }, () => generate_point()),
     });
 
     let res_upsert = http.post(url, payload, params);

**Comment by agourlay** [comment]
Have you validated in redoc that the payloads are now properly named?

**Comment by generall** [comment]
Screenshot from 2022-01-24 17-29-49

**Pull request merged**
