### PR TITLE
Cifs dir delete

### PR DESCRIPTION
**Pull request by generall**
### All Submissions:

Issue: https://github.com/qdrant/qdrant/issues/701

Overall problem is related to the unconventional behavior of the CIFS (samba) remote file system.
Being developed for windows, it has inherited some of the vices of the file systems of this family.
In particular, the file deletion procedure deviates from unix standards.

Instead of deleting the "used" file, CIFT considers it deleted, but does not release the so-called hard link.

As a result, you can observe funny visual effects:

image

This disregard for the standard was not initially considered in Qdrant.
Therefore, files could be deleted while still in use, which is perfectly normal in linux.

This PR changes that behavior. Objects must now be consumed before deleting files, which frees up file descriptors and makes deletion compatible with the CIFT snags.

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### CODE REVIEW

**Comment by generall** [comment]
@fabriziobonavita you also might be interested ;)

**Comment by agourlay** [comment]
Nice investigation :+1: 

Would we have caught this issue by running our CI test on a windows instance?

**Comment by generall** [comment]
> Would we have caught this issue by running our CI test on a windows instance?

:thinking:

**Comment by generall** [comment]
> Would we have caught this issue by running our CI test on a windows instance?

Let's see https://github.com/qdrant/qdrant/pull/706, but if it fails for other reason, I won't fix it ;)

**Pull request merged**
