### PR TITLE
fix: include jemalloc only for ARM64/AMD64 architectures

### PR DESCRIPTION
**Pull request by Dhanus3133**
Fixes: #2474
/claim #2474

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Comment by generall** [comment]
i think it should work for aarch64. At least we don't observe any problems running it.

I think it should be excluded for all architectures other than aarch64 and amd64

**Comment by Morriz** [comment]
> i think it should work for aarch64. At least we don't observe any problems running it.
> 
> I think it should be excluded for all architectures other than aarch64 and amd64

@generall A lot of people are seeing issues with jemalloc on certain arm64 platforms (like raspberry Pi, but also others, just google "jemalloc aarch64"), so dismissing those issues seems not the right way forward...is the bounty still on for making it conditional (exclude msvc and aarch64)? Personally I think that the best solution would be to set better defaults for page size depending on platform and to override it if needed with some env var. What do you think?

**Comment by generall** [comment]
Changing page size would require additional testing and is not as simple as just opt-out for specific architectures.

The current version works well enough on aws aarch64 machines which we use a lot.

**Comment by generall** [comment]
@Morriz but i am open to suggestions of how to implement it. If you could create a separate issue with the description of how to test it and make sure it won't break anything that's already working, i am happy to assign a bounty to it as well.

**Comment by Morriz** [comment]
It would be up to the user to override the page size, so imo that is none of your concern other than guidance + warnings by example in the docs. Why not just make the page size configurable and set sane defaults (RPi uses 16k, OSX also, so checking linux/darwin is a start). Your test suite should not test jemalloc and may just follow their contracts (if you design by contract that is which I promote), and they offer that parameter so why not?

**Comment by Morriz** [comment]
After reading this: https://github.com/redis/redis/pull/11407#issuecomment-1300766392,
I suggest adding `ARG JEMALLOC_PAGE_SIZE` and compiling like this:
```
JEMALLOC_CONFIGURE_OPTS="--with-lg-page=${JEMALLOC_PAGE_SIZE:-64}"
```

**Comment by Morriz** [comment]
After reading this: https://github.com/redis/redis/pull/11407#issuecomment-1300766392,
I am sad to understand the binaries use static linking and so the page size can't be made configurable. But would it be too much to ask to build one extra target prefixing the tag with `-p16` (I assume your current build is for page size 64?)

**Comment by Morriz** [comment]
I see home assistant choosing to do this: https://github.com/home-assistant/docker-base/pull/248

**Comment by Morriz** [comment]
just trying with `JEMALLOC_SYS_WITH_LG_PAGE==16` might work (see https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md)

**Comment by generall** [comment]
Sorry, I will close this in favor of https://github.com/qdrant/qdrant/pull/3945

It was the first and also more correct solution.

**Pull request closed without merging**
