### PR TITLE
use try_join_all

### PR DESCRIPTION
**Pull request by generall**
It looks cleaner for me to use `try_join_all` in this case, but maybe there are some performance pitfalls. WDYT?

P.S. also removed `.expect` as potentially dangerous.

### CODE REVIEW

**Comment by e-ivkov** [comment]
> It looks cleaner for me to use try_join_all in this case, but maybe there are some performance pitfalls. WDYT?

Exactly, FuturesUnordered are used for performance reasons
https://docs.rs/futures/latest/futures/future/fn.join_all.html#see-also

**Comment by generall** [comment]
They mention `In cases where you have a lot of futures`, but there are no clear definition of that.

**Comment by agourlay** [comment]
Looking at the source code here https://docs.rs/futures-util/0.3.21/src/futures_util/future/join_all.rs.html#119-124 it seems it fallback to `FuturesOrdered` if there more than 30 futures.

**Review by agourlay — APPROVED** [review]
I find this code much easier to read :+1: 

I would be surprised if this become a performance issue but if it does we can use `FuturesUnordered` directly where it makes sense.

**Pull request merged**
