### PR TITLE
Bump cryptography and quinn-proto dependencies

### PR DESCRIPTION
**Pull request by timvisee**
Applies <https://github.com/qdrant/qdrant/pull/5015> and <https://github.com/qdrant/qdrant/pull/5014> on `dev`.

Dependabot opened the above two PRs as a security fix. They don't affect our release build so it's tolerable to apply these to the development branch to eventually release.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Review by agourlay — APPROVED** [review]
Did some research, it seems impossible for now to tell Dependabot Alert to work on a different branch :(

**Review by ffuugoo — APPROVED** [review]

**Comment by ajayk** [comment]
> Dependabot opened the above two PRs as a security fix. They don't affect our release build so it's tolerable to apply these to the development branch to eventually release.

@timvisee would like to understand how it doesn't affect the release build  , we are using the auditable builds [here](https://github.com/wolfi-dev/os/blob/main/qdrant.yaml#L44) its getting flagged  as CVE by grype

**Comment by timvisee** [comment]
> > Dependabot opened the above two PRs as a security fix. They don't affect our release build so it's tolerable to apply these to the development branch to eventually release.
> 
> @timvisee would like to understand how it doesn't affect the release build , we are using the auditable builds [here](https://github.com/wolfi-dev/os/blob/main/qdrant.yaml#L44) its getting flagged as CVE by grype

The above dependencies are not part of our release binaries nor Docker images. They're part of our internal testing suite.

```bash
$ cargo tree --target all --all-features | grep quinn
```

**Comment by ajayk** [comment]
Thanks @timvisee for the comments really helpful 

Probably it's a bug on cargo-audit

**Pull request merged**
