### PR TITLE
Remove unecessary clippy allow deadcode

### PR DESCRIPTION
**Pull request by agourlay**
Found unnecessary clippy allow statements that we can get rid of.

### CODE REVIEW

**Review by timvisee — APPROVED** [review]
Thanks!

Maybe we can replace remaining cases with the new `#[expect(dead_code)]` to show a lint error when they have become obsolete.

**Comment by agourlay** [comment]
Yes I used the new `expect` to find some of those.
My plan was to follow up with the migration :)

**Comment by timvisee** [comment]
Fantastic!

**Comment by agourlay** [comment]
It seems the `expect` feature is suffering from false positive.

```
error: this lint expectation is unfulfilled
   --> lib/segment/src/index/field_index/geo_hash.rs:105:15
    |
105 |      #[expect(dead_code)]
    |               ^^^^^^^^^
    |
    = note: `-D unfulfilled-lint-expectations` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unfulfilled_lint_expectations)]`
```

but when removed

```
error: field `south_east` is never read
   --> lib/segment/src/index/field_index/geo_hash.rs:105:5
    |
102 | struct GeohashBoundingBox {
    |        ------------------ field in this struct
...
105 |     south_east: GeoHash, // field is not involved in the calculations, but is kept for symmetry
    |     ^^^^^^^^^^
    |
    = note: `GeohashBoundingBox` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`
``` 

I will postpone the migration for the time being :(

**Comment by timvisee** [comment]
I guess that may be because we have different compiler targets, some trigger the lint, others do not.

**Pull request merged**
