### PR TITLE
Make `LocalShard` aware of its collection id

### PR DESCRIPTION
**Pull request by coszio**
[Issues API] For implementing `UnindexedField` issues, we want to trigger them based on execution time. Since timing it at `Collection` level and above works, the best place to time it would be at the `LocalShard`, to exclude any network latencies.

Without this PR it is not possible to do the above, because we need to publish an event which includes the collection name + filters.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by generall** [comment]
Looks like an abstraction leak to me. I would rather do it completely on collection level.

**Comment by coszio** [comment]
@generall No concerns with false positives? a `POST /issues/clear` endpoint will be even more important

**Comment by generall** [comment]
But higher timing is not enough to trigger the event, right? You also need wrong configuration.

**Comment by coszio** [comment]
Yes, but not every payload key used to filter needs to be indexed, is it?

**Comment by generall** [comment]
> Yes, but not every payload key used to filter needs to be indexed, is it?

not every, but if the latency is high, pretty much for sure it is part of the problem

**Comment by coszio** [comment]
Ok, closing.

**Pull request closed without merging**
