### PR TITLE
feat: add `"any"` to `"match"` statements

### LINKED ISSUE #1196: Short form for match filtering conditions
**Is your feature request related to a problem? Please describe.**
There are situations where multiple filtering values should be applied to the same field.
The filtering criteria should consist of multiple `should` clauses, which makes request inconvenient to work with. 

**Describe the solution you'd like**
Extend query syntax to allow checking multiple values in `match` condition.

**Describe alternatives you've considered**
Extend client DSL to support automatic conversion into `should` clauses

### PR DESCRIPTION
**Pull request by coszio**
# Add support for using `any` in `match` clauses
This adds the necessary parsing and handling for filtering over a collection of values ergonomically, rather than having to write multiple match statements inside a dedicated `should`.

Resolves #1196 

This allows for the following syntax:

```json
{
    "filter": {
        "must": [
            {
                "should": [
                    {
                        "key": "city",
                        "match": {
                            "value": "New York"
                        }
                    },
                    {
                        "key": "city",
                        "match": {
                            "value": "San Francisco"
                        }
                    },
                    {
                        "key": "city",
                        "match": {
                            "value": "Tokio"
                        }
                    }
                ]
            }
        ]
    }
    ...
}
```

To be simplified into:

```json
{
    "filter": {
        "must": [
            {
                "key": "city",
                "match": {
                    "any": [
                        "San Francisco",
                        "New York",
                        "Tokyo",
                    ]
                }
            }
        ]
    }
    ...
}
```

Which makes it a lot more pleasant to write.

Should this PR be merged, I'll write the appropriate documentation in the docs repo

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by coszio** [comment]
Not sure why this is failing the `windows-latest` test, @generall do you have any pointers?

**Comment by generall** [comment]
> Not sure why this is failing the windows-latest test, @generall do you have any pointers?

Our Windows CI is somewhat unstable for some reason :disappointed_relieved: I though we fixed it, but apparently not. Will just re-run for now

**Review by generall — APPROVED** [review]

**Comment by generall** [comment]
Added also a cardinality estimation for a new condition type

**Comment by coszio** [comment]
Perfect, I'll write the documentation for this new filter feature

**Pull request merged**
