### PR TITLE
Disable incremental compilation on CI

### PR DESCRIPTION
**Pull request by agourlay**
Let's have a look at the numbers first.

### CODE REVIEW

**Comment by agourlay** [comment]
I don't see any gains, closing.

**Comment by ben1009** [comment]
> I don't see any gains, closing.

FYI, actually, the env already set, https://github.com/qdrant/qdrant/actions/runs/7693838931/job/20963364815?pr=3476#step:2:6

**Comment by agourlay** [comment]
@ben1009 Thanks for having a look at this PR :)

It seems the `rust-cache` action sets the env. variable automatically on [restore](https://github.com/Swatinem/rust-cache/blob/378c8285a4eaf12899d11bea686a763e906956af/src/restore.ts#L28)

**Comment by ben1009** [comment]
> @ben1009 Thanks for having a look at this PR :)
> 
> It seems the `rust-cache` action sets the env. variable automatically on [restore](https://github.com/Swatinem/rust-cache/blob/378c8285a4eaf12899d11bea686a763e906956af/src/restore.ts#L28)

oh, i miss that part, first the env set by https://github.com/qdrant/qdrant/actions/runs/7693838931/job/20963364815?pr=3476#step:2:6, then stored to cache in https://github.com/qdrant/qdrant/actions/runs/7693838931/job/20963364815?pr=3476#step:39:19, if have another run will fetch from cache by https://github.com/qdrant/qdrant/actions/runs/7693838931/job/20963364815?pr=3476#step:4:10 as part of cache key

**Pull request closed without merging**
