### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by generall**
### All Submissions:

Issue: https://github.com/qdrant/qdrant/issues/496

Changes:

- renamed `top` -> `limit`, to better reflect the behavior, but `top` is still available as alias, so old client are compatible with this change

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### CODE REVIEW

**Comment by agourlay** [comment]
renamed `top` -> `limit` :+1:

**Comment by agourlay** [comment]
Maybe we need an integration test showing how the pages are traversed.

It would better in terms of UX to have the total number of pages available but I am not sure it is possible.
Without this info, the user must perform repetitive search calls and increment the offset manually until the result array is empty.

**Comment by generall** [comment]
Count API has it's own task - https://github.com/qdrant/qdrant/issues/160

**Review by agourlay — APPROVED** [review]
Approving as it enables users to do more

**Pull request merged**
