### PR TITLE
exact search parameter

### PR DESCRIPTION
**Pull request by IvanPleshkov**
Issue https://github.com/qdrant/qdrant/issues/1042
This PR provides an additional search option `exact` that disables approximate search.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by generall — APPROVED** [review]

**Comment by orion512** [comment]
How can an exact search be performed on HNSW index I thought it was meant to sacrifice accuracy?
Only the FLAT index can guarantee 100% accuracy which is how I understand an exact search. Am I missing something?

**Comment by IvanPleshkov** [comment]
HNSW is a hierarchical graph with indices in vector storage that contains real vector data. Exact search iterates over whole vector storage without using HNSW

**Comment by IvanPleshkov** [comment]
> How can an exact search be performed on HNSW index I thought it was meant to sacrifice accuracy? Only the FLAT index can guarantee 100% accuracy which is how I understand an exact search. Am I missing something?

HNSW is a hierarchical graph with indices in vector storage that contains real vector data. Exact search iterates over whole vector storage without using HNSW

**Comment by orion512** [comment]
I see. Thank you very much for getting back to me.
Are you familiar with the implication that has on speed? maybe you can point me to any online resource which discusses the topic?

**Comment by IvanPleshkov** [comment]
> I see. Thank you very much for getting back to me. Are you familiar with the implication that has on speed? maybe you can point me to any online resource which discusses the topic?

Of course, the speed of the search is low. We added notification about performance to documentation (we will publish updated docs after release). We don't expect that users may use the exact search on prod. The exact search flag is an additional parameter and by default, it's turned off. This flag is for rare use cases.  For instance, for tuning of hnsw parameters

**Pull request merged**
