### PR TITLE
Better error message for untagged enum

### PR DESCRIPTION
**Pull request by Okabe-Rintarou-0**
### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:
I followed the similar issues in serde: https://github.com/serde-rs/serde/issues/2157
This will introduce a third party crate: https://docs.rs/serde-untagged/latest/serde_untagged/

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by generall** [comment]
Hey @Okabe-Rintarou-0, could you please provide an example of how the error message is improved in your PR?

**Comment by Okabe-Rintarou-0** [comment]
> Hey @Okabe-Rintarou-0, could you please provide an example of how the error message is improved in your PR?

sure, I have added a test in vectors.rs.

**Comment by generall** [comment]
> sure, I have added a test in vectors.rs

I can't see any improvement in API response error message

**Comment by Okabe-Rintarou-0** [comment]
> > sure, I have added a test in vectors.rs
> 
> I can't see any improvement in API response error message

as you can see, the error message "Unexpected vector struct" (the original message is "data did not match any variant of untagged enum VectorStruct") can be customized. What kind of error message do you want?

**Comment by Okabe-Rintarou-0** [comment]
Or could you help me locate where the relevant testing code is?

**Comment by timvisee** [comment]
Is it required to define the `Deserialize` implementation ourselves to get some useful errors back?

Because if that is the case, we'd need to do this in a lot of places which will be very cumbersome and noisy.

**Comment by ding-young** [comment]
> Or could you help me locate where the relevant testing code is?

https://github.com/qdrant/qdrant/blob/a39c8925afb81cd1307ceb2103d22b98e0448df4/lib/segment/src/types.rs#L125-L149

Hi, @Okabe-Rintarou-0 .
I don't know much about this issue... but I guess above code snippet might help you write custom err msg. :smiley:

**Comment by generall** [comment]
> as you can see, the error message "Unexpected vector struct" 

having some internal deserialization is not enough. The error is supposed to be displayed in API response.

**Comment by Okabe-Rintarou-0** [comment]
Ok, I see. 😄

**Comment by Okabe-Rintarou-0** [comment]
Maybe we can modify these codes?
https://github.com/qdrant/qdrant/blob/98339807d141f4dd081f7df229cd9f8b5855c24a/src/actix/mod.rs#L205-L233

**Comment by Okabe-Rintarou-0** [comment]
> Maybe we can modify these codes?
> 
> https://github.com/qdrant/qdrant/blob/98339807d141f4dd081f7df229cd9f8b5855c24a/src/actix/mod.rs#L205-L233

what about detect the pattern of untagged enum error, and reformat it?

**Pull request closed without merging**
