### PR TITLE
Handle bounding box crossing the 180th meridian

### PR DESCRIPTION
**Pull request by almostimplemented**
### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

* [x] Does your submission pass tests?
* [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
* [ ] Have you checked your code using `cargo clippy --all --all-features` command?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

I am not a Rust programmer. I would appreciate community assistance in adding a unit test file! We can use the reproduction example in #4102

### CODE REVIEW

**Comment by agourlay** [comment]
@almostimplemented thanks for the contribution :+1: 

Regarding adding a unit test, please have a look at the file `geo_hash.rs`, it contains some practical example of intersection and box checking using real cities.

**Comment by generall** [comment]
FYI: check_point is not the only place where this logic will be handled. We also have geohash-based index, which should be  tested (and modified) accordingly.

**Comment by almostimplemented** [comment]
@generall Can you provide some guidance for the necessary changes for the geohash code? Is that fix tightly coupled with this change? 

My team will be detecting this edge-case and splitting the bounding box into two rectangles (on either side of the 180th meridian), and I am not sure I have the bandwidth to address the geohash index changes.

**Comment by generall** [comment]
hey @almostimplemented, sure this is understandable, we don't expect you to do all the work;) my comment was addressed to whoever reviews this PR to make sure it is not merged without full support.

**Comment by agourlay** [comment]
@almostimplemented Thanks for you work, I will double check the geohash indexing and add some tests.

**Comment by agourlay** [comment]
@almostimplemented  I took the liberty of pushing tests into your PR with https://github.com/qdrant/qdrant/pull/4103/commits/97d1040e6465e71318266b267dbf83431fe712ad

My conclusion is that your fix the bug globally.

Our Geohash index links geohashes to the recorded points and uses the `GeoBoundingBox::check_point` function to filter points present in the corresponding geo hashes.

See https://github.com/qdrant/qdrant/blob/b99d507496a40b0895fff76eb2fa7a5cfdb701a9/lib/segment/src/index/field_index/geo_index/mod.rs#L358-L373

**Review by agourlay — APPROVED** [review]

**Review by timvisee — APPROVED** [review]

**Pull request merged**
