### PR TITLE
[sharding] Collection cluster info API

### PR DESCRIPTION
**Pull request by agourlay**
This PR adds a new REST API to get the collection cluster info. (#624)

With this API an operator can get extra information about the shard topology of a given collection.

It is tested via the sharding consensus test, here is an example of output.

edit: new format

```json
{
    "shard_count": 6,
    "local_shards": [
        {
            "shard_id": 2
        }
    ],
    "remote_shards": [
        {
            "shard_id": 0,
            "peer_id": 5206661873001331473
        },
        {
            "shard_id": 1,
            "peer_id": 9153846410978676289
        },
        {
            "shard_id": 3,
            "peer_id": 11473594217186723880
        },
        {
            "shard_id": 4,
            "peer_id": 17502153356522390965
        },
        {
            "shard_id": 5,
            "peer_id": 5206661873001331473
        }
    ]
}
```

### CODE REVIEW

**Comment by agourlay** [comment]
I am unsure about the current output format, maybe it would make sense to have two separate array fields `local` & ` remote` for more clarity.
Looking forward to your suggestions.

**Comment by agourlay** [comment]
Changed my mind over the weekend regarding the output format. I followed my idea regarding splitting shards.

**Comment by generall** [comment]
I would be nice to also include information about number of point in shards (at least local once)

**Comment by agourlay** [comment]
I have added the number of points on for local shards & the peer_id of the node.
The output looks like this now

```json
{
    "peer_id": 1150390019331026873,
    "shard_count": 6,
    "local_shards": [
        {
            "shard_id": 0,
            "points_count": 1
        },
        {
            "shard_id": 5,
            "points_count": 0
        }
    ],
    "remote_shards": [
        {
            "shard_id": 1,
            "peer_id": 4960188945573345192
        },
        {
            "shard_id": 2,
            "peer_id": 12995631005313377235
        },
        {
            "shard_id": 3,
            "peer_id": 15002621710623971411
        },
        {
            "shard_id": 4,
            "peer_id": 17069089910004877600
        }
    ]
}
```

**Review by generall — DISMISSED** [review]

**Comment by agourlay** [comment]
@generall it should be all green now :green_circle:

**Review by generall — APPROVED** [review]

**Pull request merged**
