### PR TITLE
add helper functions for proper handling of paths

### PR DESCRIPTION
**Pull request by hozan23**
This PR add parse_path function to src/common/helper.rs file. The function will be useful for handling config, storage, and snapshots paths. It does tilde expansion and gets the absolute path for the given path.

The function will return an error if the path does not exist.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by generall** [comment]
Why do you think this function is necessary?

**Comment by hozan23** [comment]
Hey @generall, I was about to create a new issue covering this and the idea behind it. I noticed there is no consistent way of handling the paths through the project. For the #1328  PR the code will panic if the path for the config doesn’t exist. However the paths for snapshots and storage handle differently which will make a new directory in case the path doesn’t exist. 

I am suggesting to parse/check all the paths through this function at the beginning and show a proper error message with a graceful shutdown if the path is not found.

**Comment by generall** [comment]
Why do you want to specify the storage path with absolute path in a first place?

**Comment by hozan23** [comment]
It is considered to be convenient to handle all paths as absolute paths. In practice the absolute path will be fine for all the situations regarding whether the file/directory exists or not.

**Pull request closed without merging**
