### PR TITLE
test of stream shard transfer consistency

### PR DESCRIPTION
**Pull request by generall**
This integration test highlights the problem with stream shard transfer. Not 100% of the times, but reproducible locally

### CODE REVIEW

**Comment by generall** [comment]
Found the reason for this test failing: when creating a shard transfer into a new replica, operation create State Partial for the remote shard, but doesn't create remote shard object itself. The fix is relatively simple, but creates a problem on it's own. 
If we create a remote shard on a new replica, which didn't exist before - it may produce a situation, where node A already received consensus operation, but node B, which should receive transfer, didn't. So it might be possible that we will send updates to a shard which doesn't have any local shard. If that happens - node will report an error and terminate the transfer, even though everything was working as expected.

Here are some of the possible ways to address this issue:

- ignore all errors from partial replicas (may potentially create inconsistency if failure matches the transition from partial to active)
- ignore only a specific type of errors from the partial (requires introduction of a new type of errors)
- introduce a special state that should be used before partial (too complicated)
- Force creating shard in dead (or some new) state before requesting transfer
- wait on all nodes for the receiver side to switch first (requires long operation in consensus loop)
- ???

**Comment by generall** [comment]
> What about force-creating the shard in the initiate_transfer call. We currently use that to explicitly wait for the proper shard state on the remote. We can extend it to also ensure the actual shard is there.

Do you propose to make a call to all other nodes and make sure they created remote shard?

**Comment by timvisee** [comment]
On another thought, I'm a bit puzzled this only happens with the stream transfer method.

Shouldn't the other transfer test, which the stream transfer test was based upon, suffer from the same issue?

**Comment by generall** [comment]
> Shouldn't the other transfer test, which the stream transfer test was based upon, suffer from the same issue? Our other methods are switched into Recovery first, but once we switch into Partial another node may become Partial before our target node.


No, other transfer methods are guaranteed to have remote shard object in place, as they use two-step transition. This was the only place where we forgot to create remote shard object

**Review by timvisee — APPROVED** [review]

**Pull request merged**
