### PR TITLE
Fix segment deadlock, reverse lock order during flush

### PR DESCRIPTION
**Pull request by timvisee**
Fix for segment deadlock that occurred along with the following warning:

```
WARN collection::collection_manager::holders::segment_holder: Trying to read-lock all collection segments is taking a long time. This could be a deadlock and may block new updates.
```

A deadlock could occur because we were locking multiple segments from multiple places in different orders. This solves the issue by always locking non-appendable segments before appendable ones.

I've tested this fix locally a few times with a reproducable test case.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] ~Have you written new tests for your core changes, as applicable?~
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by generall — APPROVED** [review]

**Review by ffuugoo — APPROVED** [review]
LGTM. Great job figuring this out! 🎉

**Comment by timvisee** [comment]
> LGTM. Great job figuring this out! 🎉

It always turns out to be a simple change.

**Comment by agourlay** [comment]
Late to the party.

Maybe we could change the definition of `segment_flush_ordering` to avoid one `rev`.
The function seems only used here.

**Comment by timvisee** [comment]
> Maybe we could change the definition of `segment_flush_ordering` to avoid one `rev`.
> The function seems only used here.

Seems reasonable.

Would you recommend `segment_lock_ordering` then, returning reversed results? That is a bit vague to me.

Note that `.rev()` is very efficient, it just iterates from the other side of the list. The `.reverse()` call is less efficient, but we cannot remove it with the change suggested above.

**Comment by agourlay** [comment]
Let's keep this way, I don't want to change critical code for the sake of style :+1:

**Pull request merged**
