### PR TITLE
Log sucessful gRPC request as INFO

### PR DESCRIPTION
**Pull request by agourlay**
This PR logs successful gRPC requests as INFO.

The main motivation is to have consistency with the REST API which is already doing that and to enable users of cloud to see their gRPC logs.

grpc-info

One negative aspect is that the terminal will be much more active during benchmarking after this.

### CODE REVIEW

**Review by timvisee — APPROVED** [review]
No real objection against this. I agree that it makes sense to make it consistent with REST API, even though it might have logging or even a performance impact.

> One negative aspect is that the terminal will be much more active during benchmarking after this.

Good observation.

We could temporarily disable logging using `log_level: qdrant::tonic::logging=warn,info`

**Comment by ffuugoo** [comment]
Wait, so we already have logging, just on the `trace` level? I'd then just ask cloud to enable `qdrant::tonic::logging=trace`, instead of switching it to the `info`.

**Comment by timvisee** [comment]
Just wanted to run some numbers on this because we had some concerns about performance.

I did a very rudimentary benchmark; 10 runs of 1 million bfb upsertions.

- Without logging (by default):
  ```bash
  $ ./target/perf/qdrant
  $ hyperfine -w0 -r10 "bfb -n 1000000 --skip-wait-index --indexing-threshold 10000000000000"

  Benchmark 1: bfb -n 1000000 --skip-wait-index --indexing-threshold 10000000000000
    Time (mean ± σ):     15.146 s ±  0.190 s    [User: 2.786 s, System: 0.846 s]
    Range (min … max):   14.830 s … 15.480 s    10 runs
  ```
- With logging (by default):
  ```bash
  $ QDRANT__LOG_LEVEL=qdrant::tonic::logging=warn,info ./target/perf/qdrant
  $ hyperfine -w0 -r10 "bfb -n 1000000 --skip-wait-index --indexing-threshold 10000000000000"

  Benchmark 1: bfb -n 1000000 --skip-wait-index --indexing-threshold 10000000000000
    Time (mean ± σ):     15.765 s ±  0.208 s    [User: 2.363 s, System: 0.719 s]
    Range (min … max):   15.386 s … 16.175 s    10 runs
  ```

So in this case it increases the upsertion time by about 4% if you trust the numbers.

**Comment by agourlay** [comment]
Closing this one because it could potentially generate a very large amount of logs.

It is unclear if we actually want/need this and we access logs is generally provided by a proxy in front of a deployment.

Let's keep the status quo for now and re-evaluate later if needed.

**Comment by agourlay** [comment]
I am fine with making possible for users to have more control over the logging as long as it is not on by default all the time :)

**Pull request closed without merging**
