### PR TITLE
Simplify/flatten point selection in delete vectors REST endpoint

### PR DESCRIPTION
**Pull request by timvisee**
This flattens the point selector field for the delete vectors REST endpoint. This makes point selection [consistent](https://qdrant.tech/documentation/points/#set-payload) with other endpoints.

Before:

```json
{
  "point_selector": { "points": [1, 2] },
  "vectors": ["image"]
}
```

After:

```json
{
  "points": [1, 2],
  "vectors": ["image"]
}
```

Or using a filter:

```json
{
  "filter": {},
  "vectors": ["image"]
}
```

We can still change this interface because we haven't released a version with it yet.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using `cargo fmt` command prior to submission?
3. [x] Have you checked your code using `cargo clippy` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by generall** [comment]
Is it backward compatible?

**Comment by timvisee** [comment]
> Is it backward compatible?

The delete vector endpoint is not part of any release yet, so I don't think there's any worry about it being incompatible.

This only changes the REST API, not the gRPC API or other internals.

**Comment by generall** [comment]
Made some changes to make it consistent with existing API. Also it looks like flatten enum messes up with openapi

**Comment by timvisee** [comment]
Thanks for these changes. It's a bummer the OpenAPI generator doesn't support `#[serde(flatten)]` but this is a good middle ground.

I like that the REST API now supports providing both point IDs and a filter.

Would you mind to approve?

**Review by generall — APPROVED** [review]

**Pull request merged**
