### PR TITLE
Optimize inverted index

### LINKED ISSUE #1604: Optimize memory consumption of the Inverted Index
Optimize memory consumption of the Inverted Index

**Is your feature request related to a problem? Please describe.**
The full-text index uses inverted index to perform filtering and retrieval fast.
But the implementation of inverted index is naive and consumes a lot of memory.
Especially when the number of documents is large, and we use prefix tokenization.

It can quickly consume lots of memory for even a medium-sized dataset.

Inverted index is located here:
https://github.com/qdrant/qdrant/tree/master/lib/segment/src/index/field_index/full_text_index

Instructions how to use it in qdrant:
https://qdrant.tech/documentation/indexing/#full-text-index

**Describe the solution you'd like**

Optimize the in-memory representation of inverted index.
Avoid using `String` as a key in the hash set.
Use a more compact representation of the inverted index.

Ideally, the new implementation should be able to use the exising persistent storage format, but build the inverted index in a more compact way.

**Describe alternatives you've considered**
It might be required to change the persistent storage format as well, to make it more compact.
If you find it necessary, it will be required to also implement a migration logic for the existing storage.

**Additional context**

Acceptance criteria:

- At least 2x memory consumption reduction for the inverted index, actually it should be possible to reduce it 5x or more
- Search performance should not be affected (at least not significantly)
- Build time should not be affected (at least not significantly)
- Functionalities of the inverted index should be preserved

Experimental data:

- Feel free to use this snapshot for testing: https://storage.googleapis.com/qdrant-common-shared/startups-8476456695034750907-2023-03-25-09-41-29.snapshot.gz

```
gzip -d startups-8476456695034750907-2023-03-25-09-41-29.snapshot.gz

cargo run -r --bin qdrant -- --snapshot path/to/startups-8476456695034750907-2023-03-25-09-41-29.snapshot:startups
```

### PR DESCRIPTION
**Pull request by Weijun-H**
This pr will close #1604

The optimization will take the following steps:
- [x] replace `string` in `postings` by `trie`
- [x] update `point_to_docs` to avoid `BTreeSet<String>`
- [x] optimize `Document`
- [ ] benchmark

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by Weijun-H** [comment]
Hi @generall, do you know of an accessible method to measure memory consumption? I want to evaluate the current implementation. Thank you.

**Comment by generall** [comment]
you can check htop after reboot. It is not reliable if you upload data, but on a cold start it should be fine

**Comment by Weijun-H** [comment]
After optimization, the memory usage is still the same as the original. So I'm not convinced that the sudden increase in memory usage is due to an inverted index. I will continue to explore this problem this week.
original_mem

optimized

**Comment by generall** [comment]
when I try to load test snapshot, it gives me
```
[2023-03-27T00:35:30.594Z ERROR qdrant::startup] Panic occurred in file /home/generall/projects/vector_search/qdrant/lib/collection/src/shards/replica_set.rs at line 495: Failed to load local shard "./storage/collections/startups/0": Service internal error: Failed to deserialize document: invalid type: sequence, expected a boolean
```

**Comment by Weijun-H** [comment]
> 

When I ran the command 
```
gzip -d startups-8476456695034750907-2023-03-25-09-41-29.snapshot.gz

cargo run -r --bin qdrant -- --snapshot path/to/startups-8476456695034750907-2023-03-25-09-41-29.snapshot:startups
```
it worked.

**Comment by generall** [comment]
Ok. I found the problem. It seems that after recovering snapshot in a new version, it is no longer compatible with the old one.

But I can confirm that the memory usage didn't improve

**Comment by Weijun-H** [comment]
I tried to check the memory usage when running `cargo run -r --bin qdrant`. The weird thing happened, the figue still is same as the version running `--snapshpt`. Could anyone have a look and give me some hints? Thanks! @generall 
optimized

**Comment by Weijun-H** [comment]
The issue is completed by #1677

**Pull request closed without merging**
