### PR TITLE
introducing two new payload schema type: integer_lookup & integer_range

### PR DESCRIPTION
**Pull request by dzhao**
introduce two new index types:
integer_lookup: it only creates a hash index
integer_range: it only creates a btree index
This is useful for two use cases where both payload indexing and hnsw
indexing will be reduced:
1. for example: posts with a payload user_id. In this case, we just need
   to lookup a user_id, hence no need for a btree index
2. for example: posts with a payload creation_ts. In this case, we just
   need to lookup posts based on a range filter, hence no need for a
   hash index

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by timvisee — COMMENTED** [review]
Great idea, these make a lot of sense. Thanks for implementing it!

I do wonder whether we want to take this route though, of defining a new index type for each variant. Instead we may be able to use the same `"int"` but with some `{"lookup": true, "range": true}` properties to achieve the same, even though we don't have infrastructure for this at this time.

Question, if I may: have you tested these new types in practice? And if possible, could you share some results?

**Comment by dzhao** [comment]
will test the new types soon. 
I would slightly prefer flatten the type instead of adding attributes. "lookup", "range" won't be applicable to geo or text based index.

**Comment by dzhao** [comment]
tested this. especially integer_lookup would speed up hnsw building quite significantly since it no longer needs to build subgraphs for btree ranges. Let me know if you are ok with merging. I am open to have better configuration options

**Comment by timvisee** [comment]
> tested this. especially integer_lookup would speed up hnsw building quite significantly since it no longer needs to build subgraphs for btree ranges. Let me know if you are ok with merging. I am open to have better configuration options

Cool! Thanks for letting us know.

In the mean time I've implemented a parameterized variant in <https://github.com/qdrant/qdrant/pull/3380>. It would be fantastic if you could let us know if you have any comments on it.

Everything should be have the same, instead for the API interface. I've also cherry-picked your test into it. I still have to confirm it's actually compatible with our API definitions and clients, so that question remains for a bit.

**Comment by timvisee** [comment]
Closing this since <https://github.com/qdrant/qdrant/pull/3380> is merged. Thanks a lot for your initial efforts on this @dzhao!

**Pull request closed without merging**
