### PR TITLE
Fix flaky integration telemetry test

### PR DESCRIPTION
**Pull request by coszio**
Addressing a [flaky e2e test that was failing](https://github.com/qdrant/qdrant/actions/runs/4751196940/jobs/8440094308#step:9:2689) due to surprising format "change". This makes it more resilient on decimal precision changes

### CODE REVIEW

**Review by timvisee — APPROVED** [review]
Nice! :)

I took the liberty to assign myself as reviewer.

**Comment by generall** [comment]
unfortunately, `fromisoformat` is broken in python =(

**Comment by generall** [comment]
tried that already

**Comment by coszio** [comment]
I had tested it locally and it worked, I am now realizing it seems to be fixed for python 3.11, which is the one I was using. Should we make a workaround for this, or try to upgrade python?

**Comment by coszio** [comment]
Bumping the python version to 3.11 and updating requirements-freeze.txt looks ok 👍

**Comment by generall** [comment]
> I had tested it locally and it worked, I am now realizing it seems to be fixed for python 3.11, which is the one I was using. Should we make a workaround for this, or try to upgrade python?

If we can upgrade python in tests, it should be fine

**Review by generall — APPROVED** [review]

**Pull request merged**
