### PR TITLE
skip pre-heat if limited memory

### PR DESCRIPTION
**Pull request by generall**

### CODE REVIEW

**Review by timvisee — COMMENTED** [review]
What about a global variable with the current total amount of preheated bytes? We increase this when preheating. If it surpasses the amount of memory we have, we stop preheating new segments. This can be global because memory availability is global, on restart it is back to zero.

The current implementation is simple and also fine. I figured the above approach is a bit better at handling upto what we actually have available.

**Comment by generall** [comment]
> What about a global variable with the current total amount of preheated bytes? 

that could work for initial heat-up, but won't work for heating after optimization.

**Review by ffuugoo — APPROVED** [review]
LGTM.

I think that both approaches could complement each other. Like, skip memmaps that won't benifit from prefaulting, and prefault the smaller ones while they still fit into memory.

**Review by timvisee — APPROVED** [review]
Approving because the current approach is okay.

We can investigate the [other](https://github.com/qdrant/qdrant/pull/2086#pullrequestreview-1480891198) named approach at another time.

**Pull request merged**
