### PR TITLE
Fix overeager marking of visited points during search

### PR DESCRIPTION
**Pull request by Apmats**
This PR resolves https://github.com/qdrant/qdrant/issues/2863

When creating a payload index, recall performance significantly deteriorates. 
I also tested searching with extremely high `hnsw_ef` values which didn't help with recall - which pointed me to a disconnected graph and I audited the graph construction code but couldn't find any case where it's being significantly mangled!

Eventually I found a bug in the search logic (which also somewhat affects graph construction, but from testing it's not as big of a problem there as much as it's on query time behavior).

The problem: When searching on a graph level and we're examining a node, we consider and score only `m` links (this is so that we prioritize the original `m` links instead of following the added links that came from payload indexing). However, before doing this, we have marked all links as visited (both the first `m` from the original graph as well as all the added payload links).
This means that these points are never really examined but they are marked as such, and this means that certain parts of our graph are never visited during search.

The fix: simply only mark as visited the points that have been actually considered in the search.

Question to maintainers: Do you think this warrants a test? The test should be easy to write (generate 2 linked points with `n` links with overlap like this eg for `n` = 4 create points idx1 [2, 3, 4, 5] idx2 [ 4, 5, 6, 7], set `m` to half of `n` eg. 2 in the previous setup, and observe that points are visited as expected). At the same time, this is a very specific bug tied a bit too closely to the implementation.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by timvisee** [comment]
I didn't drive into the details yet. But do you see a noticeable difference when testing this locally?

**Comment by Apmats** [comment]
@timvisee oh yeah - I failed to mention, this solves the issue in my situation, restoring my recall back to the expected number, even without rebuilding the graph (meaning just loading a collection built with the previous code and searching with the fix in place)!

**Review by timvisee — APPROVED** [review]
Thank you so much for picking this up! 

Looks good to me. But I'd like to see the opinion of @generall and @IvanPleshkov as well.

**Review by generall — APPROVED** [review]
I can confirm that this changes do improve the search accuracy in case of payload index presence and search query without a filter.

The changes also makes total sense, @Apmats thanks a lot for this fix!

**Review by IvanPleshkov — APPROVED** [review]

**Pull request merged**
