### PR TITLE
Snapshot storage on S3 via SnapshotManager abstraction

### LINKED ISSUE #3324: Snapshot storage on S3
**Is your feature request related to a problem? Please describe.**

Related issue: https://github.com/qdrant/qdrant/issues/1703

Currently qdrant can only store snapshots in local filesystem (even if it is a mounted s3 bucket), but it might be convenient to upload and download snapshots from S3 directly.

**Describe the solution you'd like**

Ability to configure snapshot directory as S3 bucket, specifying access credentials.
It should be possible to list snapshots saved on attached S3 bucket as well.

**Describe alternatives you've considered**

Our current recommendations are to mount s3 as local fs, but it might be non-trivial to do in some environments.

**Additional context**

Important qualities of the solution:

- Solution should not change default behavior and should be backward compatible
- Additional dependency to work with S3 should be have reasonable size, do not contribute significantly into qdrant compile time & binary size
- Should work with all types of S3-compatible storage, not only aws, but also google storage, minio, e.t.c.

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

### PR DESCRIPTION
**Pull request by mogery**
Fixes #3324
/claim #3324

This PR adds a new package, `snapshot_manager`, which houses the `SnapshotManager` struct. The `SnapshotManager` abstracts (`SnapshotFile`) the filesystem-dependent parts of snapshots away from the rest of the codebase, which allows us to write two "backends" for snapshot storage: local and S3.

The local backend is 99% ported over from the existing code. Most of the trouble is with adjusting the existing code to use this new interface.

The S3 backend is built with the `rust-s3` crate, which I've found to be the most reliable. It's battle-tested by having a million all-time downloads, it supports non-AWS S3-compatible file storage services, etc.

This is a biiiig PR which changes a considerable amount of code structure. Let me know if you like it or not. I'll be doing a larger sweep of all my changes to catch structure mistakes once the todo's finished.

## To-do

- [x] Finish porting local backend and adjusting code for compatibility (won't build without this, don't try)
- [x] Add S3 backend
- [ ] Write tests?
  - _Does this need explicit testing? S3-specific testing would be good, but I'm not sure where we could get a mock for that._
- [x] Update docs with config changes

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by mogery** [comment]
alright, everything is working on local! i have confidence i can build this now. onto S3

**Comment by mogery** [comment]
Screenshot 2024-01-22 at 03 29 57

\*mad scientist laughter\*

**Comment by mogery** [comment]
I'm opening this as ready for review, but take it more as "request for comments". Everything seems to work after messing around a bit, but I haven't tested for any accidental breaking API or backwards compatibility issues.

/claim #3324

**Comment by generall** [comment]
Hey @mogery, thanks for the PR!
It is indeed huge and would take significant time to review all together. 
I would appreciate if you could split this PR into several independent ones, it would significantly speed up the review.

**Comment by mogery** [comment]
> I would appreciate if you could split this PR into several independent ones, it would significantly speed up the review.

Hey, it's sort of hard to split, since it's an architectural change, and I can't really break it down without breaking build. I could break it down into two: one that just switches everything to use SnapshotManager, and another one which adds S3 support to it, but I'm not sure how much that would help.

**Comment by mogery** [comment]
@generall Could you please run the workflows again? I cannot reproduce any of the issues locally.

**Comment by mogery** [comment]
sorry, sent that message right before realizing that i was running the tests in the wrong directory...

anyways, i've fixed everything up now. all tests run for me on local both with the local backend and with S3. hopefully this time it all passes on your side too

**Comment by mogery** [comment]
i've also verified that nothing is present in the snapshot folder (at idle, temp files are still created now and then) when using S3

**Comment by mogery** [comment]
I'm very confused. All the integration tests run successfully on my local machine. [Here's a log.](https://gist.github.com/mogery/bd2167c55d8c4c3b468c2403582fb147)

**Comment by mogery** [comment]
Another round of fixes done. Ran even more tests on local, everything is coming back green.

**Comment by mogery** [comment]
Heh, I didn't see that that one failed, because I couldn't see the exit code. Anyways, should be fixed. Thanks for bearing with me.

**Comment by mogery** [comment]
I'll also be running the whole test suite while mounted to S3 tomorrow.

**Comment by mogery** [comment]
hi there @generall, any updates on reviewing this?

**Comment by generall** [comment]
hey @mogery, review of that big pr requires about 4 hours uninterrupted timeframe. If possible, could you please split it into smaller pieces?

**Comment by mogery** [comment]
@generall Closing this PR and splitting it into two.

**Comment by mogery** [comment]
Superseded by #3520 and [TBD]

**Pull request closed without merging**
