### PR TITLE
Optimize strings ram usage for map index

### PR DESCRIPTION
**Pull request by IvanPleshkov**
This PR optimizes RAM usage for map index.

There are 2 ram optimization improvements:
1) Avoiding string duplications
2) Small string optimization

### Avoiding string duplications
Map index is bimap between value and point id. There are maps `HashMap<String, BTreeSet<PointOffsetType>>` and `Vec<Point, Vec<String>>` in `MapIndex`. For each string value there is a second string copy in second map.
To avoid it, it's possible to use `Arc<String>`. But this solution has drawbacks: additional indirection and additional ram usage for `Arc` containment.
It's possible to use `Arc<str>` which avoids drawbacks. Read more here:
https://github.com/rust-lang/rfcs/blob/master/text/1845-shared-from-slice.md

Drawback of `Arc<str>` is a string reallocation for conversion from `String` into `Arc<str>` while key inserting. Is the case of this PR it's acceptable because in `dev` we also make a string copy for inserting in second maps.

### Small string optimization

Small string optimization (SSO) is a common optimization trick for C++. `String` contains 3 pointers for start, end, and capacity. In 64-bit arch, it's `3 * 8 = 24` bytes. If string is small it's better to use these bytes instead of allocation.

### Implementation details

String for the map index is defined as an enum:
```
pub enum MapIndexString {
    Heap(Arc<str>),
    Stack([u8; 23]),
}
```

Which allows using SSO for small strings and shared `Arc<str>` for large string. In both cases, there is a RAM usage profit.

Size of this enum is 24 (for 64-bit arch). It's equal to the general String size.

### RAM difference

For H&M dataset with mmaped payloads, hnsw and vector storage there is 18MB difference. Total size (with disabled mmap pages prefault) decreased from 678MB to 660MB. Not so much but it's zero cost optimization and H&M dataset has short strings and also a numeric field indexes

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by timvisee** [comment]
Cool stuff! Do we have any measurable improvement when using this in a realistic use case?

**Comment by llogiq** [comment]
Why not use a small string crate like [smolstr](https://docs.rs/smol_str) or [flexstr](https://docs.rs/flexstr)?

**Comment by timvisee** [comment]
> Why not use a small string crate like [smolstr](https://docs.rs/smol_str) or [flexstr](https://docs.rs/flexstr)?

I asked about this during our daily. This is mainly about string sharing, not about small strings. So this efficiently shares strings to minimize RAM usage. As a bonus a small string variant is added on the shared string enum. This is used when the string is smaller or equal to the size of the shared string pointers (in memory). I hope that makes sense.

The above crates do not provide good primitives to achieve the above.

@IvanPleshkov Please correct me if I got this wrong.

**Comment by IvanPleshkov** [comment]
> > Why not use a small string crate like [smolstr](https://docs.rs/smol_str) or [flexstr](https://docs.rs/flexstr)?
> 
> I asked about this during our daily. This is mainly about string sharing, not about small strings. So this efficiently shares strings to minimize memory usage. As a bonus a small string variant is added on the shared string enum. This is used when the string is smaller or equal to the size of the shared string pointers (in memory), because in that case sharing would only introduce overhead. I hope that makes sense.
> 
> The crates you mentioned do not provide good primitives to achieve the above.
> 
> @IvanPleshkov Please correct me if I got this wrong.

I checked `smol_str`, and there is an immutable string with all required trait implementations.
https://github.com/rust-analyzer/smol_str/blob/master/src/lib.rs#L411
Thank you for sharing this lib @llogiq! It seems that this crate is good enough for our purposes

**Comment by timvisee** [comment]
> It seems that this crate is good enough for our purposes

Cool! :smile:

**Comment by IvanPleshkov** [comment]
> Why not use a small string crate like [smolstr](https://docs.rs/smol_str) or [flexstr](https://docs.rs/flexstr)?

Integrated https://docs.rs/smol_str crate. This crate has an immutable string like my options but with additional optimization that allows contain on the heap one more byte

**Comment by IvanPleshkov** [comment]
> Cool stuff! Do we have any measurable improvement when using this in a realistic use case?

For H&M dataset with mmaped payloads, hnsw and vector storage I got 18MB difference. Total size (with disabled mmap pages prefault) decreased from 678MB to 660MB. Not so much but it's zero cost optimization and H&M dataset has short strings and also a numeric field indexes

**Comment by timvisee** [comment]
Thanks for measuring! Any improvement is an improvement. Great work.

**Review by generall — APPROVED** [review]

**Pull request merged**
