### PR TITLE
Add Actix and config validation

### PR DESCRIPTION
**Pull request by IvanPleshkov**
_Continuation by @timvisee:_

Implements validation on configuration files and Actix endpoints (path parameters, query parameters and JSON payload). This improves quality of life for end users and prevents issues like [this](https://github.com/qdrant/qdrant/issues/1435).

It uses the [`validator`](https://github.com/Keats/validator) and [`actix-web-validator`](https://github.com/rambler-digital-solutions/actix-web-validator) crates to implement this replacing the old validation logic.

This also reworked error handling a bit for Actix; a wrongly formatted JSON payload now gets a nice JSON error response with a correct status code.

I've added some arbitrary validation limits to things throughout the project next to what @IvanPleshkov had already set. Someone with better knowledge of the internals should go through these limits (and should define more where necessary). The changes in this PR at least make it a ton easier to change these limits in the future.

Expensive endpoints such as the batch upsert have limited validation; those simply ensure the number of IDs and vectors match, and doesn't iterate through every single vector.

A gRPC implementation for validation will be done in a separate PR.

#### Config validation

Starting with invalid settings (`config.yaml`) will show warnings in the console and then continues operation:

image

Internal configurations are validated as well, for example the configuration attached to a collection in storage:

image

#### Path validation

Path parameters are validated. For example, a collection name that is too long:

```json
{
    "result": null,
    "status": {
        "error": "Validation error in path parameters: [name: value \"longnamehere...\" invalid, must be from 1 to 255 characters]"
    },
    "time": 0.0
}
```

#### Query validation

Providing an invalid query parameter errors as well. For example, `?timeout=0` gives you the error:

```json
"Validation error in query parameters: [timeout: value 0 invalid, must be 1.0 or larger]"
```

#### Payload validation

JSON payload is also validated. For example, when creating a collection with an illegal configuration:

```json
{
  "hnsw_config": {
    "m": 1,
    "ef_construct": 3,
  },
  "optimizers_config": {
    "memmap_threshold": 100
  }
}
```

You get the error

```json
"Validation error in JSON body: [hnsw_config.m: value 1 invalid, must be from 4.0 to 10000.0; hnsw_config.ef_construct: value 3 invalid, must be 4.0 or larger; optimizers_config.memmap_threshold: value 100 invalid, must be 1000.0 or larger]"
```

If upserting a batch with a different number of IDs and vectors:

```json
{
    "batch": {
        "ids": [1, 2, 3],
        "vectors": [
            [0.9, 0.1, 0.1],
            [0.1, 0.9, 0.1]
        ]
    }
}
```

You'll get:

```json
"Validation error in JSON body: [batch: number of ids and vectors must be equal (3 != 2)]"
```

### Tasks
- [x] Ensure used crates are maintained, maybe fork ourselves?
- [x] Remove old validation logic
- [x] Add validation for settings/configuration
- [x] Add validation to path parameters
- [x] Add validation to query parameters
- [x] Add validation for JSON payload
- [x] Show pretty warnings (https://github.com/qdrant/qdrant/pull/1463#issuecomment-1427751873)
- [x] Respond with pretty deserialize/validation errors from the Actix API
- [x] Limit validation on expensive endpoints. (e.g. on batch upsert, only validate some counts)
- [x] Don't panic when validation fails for a configuration (https://github.com/qdrant/qdrant/pull/1463#issuecomment-1427751873)
- [x] Update OpenAPI spec for new HTTP statuses (errors not further specified, already covered by 4XX errors).
- [x] ~Add validation to grpc API (maybe as next PR)~

Thanks @IvanPleshkov for your initial work on this! ~ @timvisee 

### Todo
- If this is accepted, we can remove this fork: https://github.com/qdrant/validator/
- Start on gRPC implementation

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by generall** [comment]
ToDo:

1. Pretty error message `"Validation error: optimizers_config.memmap_threshold: Validation error: range [{\"value\": Number(100), \"min\": Number(1000.0)}]"`
2. Validate `Settings` on service start and show warnings if validation fails (but do not panic)

**Comment by timvisee** [comment]
I think this is ready. I've updated the [main](https://github.com/qdrant/qdrant/pull/1463#issue-1579600316) description with all changes.

**Comment by timvisee** [comment]
I think this is ready. I've updated the [main](https://github.com/qdrant/qdrant/pull/1463#issue-1579600316) description with all changes.

**Review by generall — APPROVED** [review]
Can't complain about anything!

**Pull request merged**
