### PR TITLE
Use Semver type in version info response

### PR DESCRIPTION
**Pull request by timvisee**
`schemars` supports the semver type. Since we expose a semver I decided to explore the idea of using the respective type there.

As shown in the OpenAPI specification this constrains the allowed pattern to match the semver specification. Though not necessary, I think that's a valid addition.

Any objections or thoughts?

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### CODE REVIEW

**Review by agourlay — APPROVED** [review]
Fine for me if the Python REST client is fine :)

**Comment by timvisee** [comment]
> Fine for me if the Python REST client is fine :)

Yeah, I'll give checking that a shot.

**Comment by timvisee** [comment]
> Fine for me if the Python REST client is fine :)

Generating the REST client and running integration tests works fine :+1:

**Comment by generall** [comment]
> Any objections or thoughts?


no objections, but what problem does it solves?

**Comment by timvisee** [comment]
> no objections, but what problem does it solve?

None.

It just adds more type information. Since that is supported out of the box I figured; why not.

**Comment by timvisee** [comment]
Closing this since I don't think we're enthusiastic enough about this change :smile:

**Pull request closed without merging**
