### PR TITLE
Refactor `lib/common` to support adding sub-crates to "common"

### PR DESCRIPTION
**Pull request by ffuugoo**
This PR changes `lib/common` structure a bit, to allow adding sub-crates under `lib/common` directory.

The motivation for this is to be able to add common code with "heavy" dependencies (e.g., `tokio`/`reqwest`/etc) without adding these transitive dependencies to the crates that don't need them (e.g., `api`).

- `lib/common` is moved to `lib/common/common`
- there's a "fake" `common-workspace-stub` crate inside `lib/common` now
  - with a weirdly placed `lib/common/lib.rs` file
  - this is a hack to allow using wildcards in the main `Cargo.toml`
  - e.g.:
    ```
    [workspace]
    members = ["lib/*", "lib/common/*"]
    ```
  - without these hacks
    - `lib/*` wildcard would fail, if there's no `lib/common/Cargo.toml`
    - and `lib/common/*` wildcard would fail, if there's `lib/common/src` directory without `Cargo.toml`

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] ~~Have you written new tests for your core changes, as applicable?~~
* [ ] ~~Have you successfully ran tests with your changes locally?~~

### CODE REVIEW

**Comment by generall** [comment]
Hi @ffuugoo, could you please elaborate why this is better than just a single `common` crate?

**Comment by ffuugoo** [comment]
> Hi @ffuugoo, could you please elaborate why this is better than just a single `common` crate?

Easier to add `common` crates that has heavy dependencies that aren't needed by most of other crates under `lib`. (Bascally, see #2552.)

**Comment by timvisee** [comment]
What about a single `common` crate with feature flagged sub-modules? Or do we expect that to create another form of dependency hell?

E.g.:

```toml
[dependencies]
common = { path = "../common", features = ["download"] }
```

**Comment by agourlay** [comment]
I find the `common/common` a bit weird TBH.

> The motivation for this is to be able to add common code with "heavy" dependencies...

Instead of doing sub crates within `common` why not creating dedicate crates at the same level for it?

I don't have experience with projects having deeper sub crate structure like you propose.

**Comment by ffuugoo** [comment]
> Instead of doing sub crates within `common` why not creating dedicate crates at the same level for it?

Sure, we can do that. Though, I feel like some kind of `common` directory for small dependencies would be more convenient.

**Comment by agourlay** [comment]
Taking my personal case as an example.

I need to move in common.
- `madvise.rs`
- `mmap_ops` 
- `file_operation` 

That is adding the following dependencies to the common crate
- memmap2 = "0.7.1"
- parking_lot = "0.12.1"
- tempfile = "3.8.0"
- atomicwrites = "0.4.1"

Are those small enough to join the common crate or would you recommend the split?

I am trying to understand if it makes sense to do the split now or when we actually need it.

**Review by timvisee — COMMENTED** [review]
After another pass, I like the idea of having sub-crates in `common`. There are some real benefits here with regards to dependencies.

However, I do think we should remove and split up `common/common`.

My suggestion would be:
* `common/common/src/validation.rs` -> `common/validation/`
* `common/common/src/fixed_length_prio_queue.rs` -> `common/queue/`

And @agourlay's items:
* `madvise.rs` -> `common/vm/` (or `memory`)
* `mmap_ops` -> `common/vm/`
* `file_operation` -> `common/io/`

What do you think?

**Comment by agourlay** [comment]
I like @timvisee proposal.

Otherwise renaming `common/common` to `common/utils` is fine for me me.

**Comment by ffuugoo** [comment]
> I like @timvisee proposal.
> 
> Otherwise renaming `common/common` to `common/utils` is fine for me me.

@agourlay @timvisee Should we merge this then?

Also, please, when you'll be factoring-out more stuff to the `common`, name memory module `memory` or `mem`. Even I have to pause for a second sometimes to remember that `vm` is "virtual memory". 😭🙏

**Comment by timvisee** [comment]
In our daily we agreed on keeping this as-is. We can always in change this if we decide on something different in the future.

**Review by timvisee — APPROVED** [review]

**Review by agourlay — APPROVED** [review]
Sorry for the bikeshedding :+1:

**Pull request merged**
