### PR TITLE
cargo +nightly fmt

### PR DESCRIPTION
**Pull request by coszio**
Something's changed in latest nightly rustfmt. All these changes are only from `cargo +nightly fmt` on `dev`.

An alternative solution would be to ditch the nightly formatting, but I'm not sure which is option is better.

### CODE REVIEW

**Comment by timvisee** [comment]
It seems that our CI formatter/linter currently fails on this.

I think we should wait a little and see if this remains the case. It may very well be an accidental change in nightly that gets reverted tomorrow.

**Review by timvisee — COMMENTED** [review]
It seems that our CI formatter/linter currently fails on this.

I think we should wait a little and see if this remains the case. It may very well be an accidental change in nightly that gets reverted tomorrow.

We may merge when CI starts failing without these changes.

**Comment by coszio** [comment]
> It may very well be an accidental change in nightly that gets reverted tomorrow. 

Hopefully 🤞

**Comment by ffuugoo** [comment]
https://github.com/rust-lang/rustfmt/issues/5964

**Pull request closed without merging**
