### PR TITLE
Remove deprecated `PointsUpdateOperation` variants

### PR DESCRIPTION
**Pull request by coszio**
In Qdrant 1.7, we deprecated these fields. ~For 1.8, we can safely remove them.~ Edit: We will remove these eventually

Related PR: qdrant/qdrant-client#502

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by timvisee — APPROVED** [review]

**Comment by coszio** [comment]
@generall do we want this change here, or only in client side?

**Comment by generall** [comment]
Only on client side for now

**Comment by coszio** [comment]
Drafting then

**Comment by coszio** [comment]
Closing, since it is an easy change to do when we want to do it

**Pull request closed without merging**
