### PR TITLE
Promote anyhow to workspace

### PR DESCRIPTION
**Pull request by agourlay**
Centralize `anyhow` version.

### CODE REVIEW

**Comment by generall** [comment]
I would rather prefer to get rid of anyhow inside the storage instead

**Comment by agourlay** [comment]
> I would rather prefer to get rid of anyhow inside the storage instead

It seems to be used only within the `consensus_manager` to add context messages on the consensus persistence application.

Do you prefer having a dedicated error variant instead?

**Comment by generall** [comment]
> Do you prefer having a dedicated error variant instead?

I am thinking about it, yeah

**Comment by agourlay** [comment]
The workspace promotion makes less sense if we are trying to decouple our library crates from anyhow.

**Pull request closed without merging**
