### PR TITLE
Skip serializing null fields in `Record` and `ScoredPoint` (REST)

### PR DESCRIPTION
**Pull request by coszio**
With the intention of making the interface simpler, I propose to skip serializing the optional fields in `Record` and `ScoredPoint`.

From my POV, this has two advantages:
- Less noise in the response when `with_payload` and `with_vector` are not requested.
- Less confusion from users thinking their points don't have payload/vector ("It says payload is null!")

Python client will keep deserializing them into their classes as `None` fields, though, so the advantages only apply when doing plain REST requests.

### CODE REVIEW

**Comment by coszio** [comment]
@Anush008 Do you know if this would a breaking change with other clients/integrations?

**Comment by Anush008** [comment]
I will have to take a look. Will update here.

**Comment by Anush008** [comment]
The integrations should all be good. Java and C# clients use gRPC. So shouldn't affect those as well.

**Comment by coszio** [comment]
Drafting to prevent merging before a patch release

**Review by generall — APPROVED** [review]

**Pull request merged**
