### PR TITLE
fix: segment_builder_test::test_building_cancellation

### LINKED ISSUE #2723: Flaky test `segment_builder_test::test_building_cancellation`
### System error

```text
baseline time: 9921
thread 'segment_builder_test::test_building_cancellation' panicked at 'time_later: 2813, late_stop_delay: 1984', lib\segment\tests\integration\segment_builder_test.rs:172:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Context

Date: 25.09.2023 09:59

[Flaky failure run](https://github.com/qdrant/qdrant/actions/runs/6297499749/job/process-results)

[Commit](https://github.com/qdrant/qdrant/tree/840248f6fcddcd27bef686ccaf70af4afe67f0ee)

OS: windows-latest

Branch: refs/heads/dev

#

### PR DESCRIPTION
**Pull request by jkcs**
close #2723

**A Novice's Attempt at Rust, If there are any issues, please point them out. Thank All.**

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by generall** [comment]
Hi @jkcs, could you please provide some explanations for the changes?

**Comment by timvisee** [comment]
Hi @jkcs. I don't think I understand how this solves the flaky tests.

> In my understanding, this is essentially a thread synchronization issue. The assertion within `baseline_segment` stipulates that it must complete within 20 seconds;

No, the baseline test should run longer than 20 seconds. But it will be cancelled in 20 seconds to get some baseline on how long running for 20 seconds and cancelling takes.

> Ideally, there should be no need for a timeout duration.

That's right, but there does not seem to be any better or more reliable way to test for cancellation (within time!) without depending on some timeout.

> When executing baseline_segment, there is no need to set a timeout; we simply wait for its completion to obtain the time_baseline value.

I think we do, because it is not a baseline measurement for completion, but a baseline measurement for 20 seconds plus cancellation. The function will simply return an error if it was not cancelled.

**Comment by timvisee** [comment]
@jkcs I don't see how this solves this being flaky.

All logic still seems to be the same, except for removing the _timeout_ for the baseline measurement. I don't see how using a callback here is different than implementing the timeout/cancellation in the function directly.

If I recall correctly, the flakiness actually comes from the short and long tasks taking a longer/shorter time to cancel than we expected, possibly because the CI machine is busy with a lot of other things.

Maybe I'm missing something important. If you think I do, then could you please: 1. explain what you think the problem is, in more detail. 2. how your approach specifically solves this problem.

**Comment by timvisee** [comment]
> Sorry, I haven't fully grasped this issue yet. This attempt has failed, and the PR is closed.
> 

No problem. We haven't either! 😁

Thank you for giving it a shot.

**Pull request closed without merging**
