### PR TITLE
add OCI labels on docker image

### PR DESCRIPTION
**Pull request by agourlay**
Exploring https://github.com/qdrant/qdrant/issues/2572

Context: https://github.com/opencontainers/image-spec/blob/main/annotations.md

This makes one more version to update.

### CODE REVIEW

**Comment by generall** [comment]
How do we propagate version from cargo?

**Comment by generall** [comment]
Maybe set it in the build script?

**Comment by bashofmann** [comment]
You can add labels while building the image with `--label`.

**Review by timvisee — APPROVED** [review]

**Comment by agourlay** [comment]
Unsure how to fully test this without a making a release.

**Pull request merged**
