### PR TITLE
fix: Implement better handling of OOD issues in optimizer

### PR DESCRIPTION
**Pull request by varshith257**
/claim https://github.com/qdrant/qdrant/issues/4297
### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Summary of Changes

# New Features

- Introduced disk space checks before indexing segments to ensure sufficient space is available.
- Added error handling for "No space left on device" conditions during item insertion.

# Bug Fixes

- Enhanced low disk space test scenarios to cover both search and indexing operations.

### CODE REVIEW

**Comment by varshith257** [comment]
@generall I have added all related code for the scenario of disk overflow for the tests here https://github.com/qdrant/qdrant/pull/4267

Can we add those tests here to check the functionality of the above tests better? WDYT?

**Comment by generall** [comment]
Hey @varshith257, thanks for the attempt, but unfortunately there is another solution, which I think is a bit cleaner. 

Close in favor of https://github.com/qdrant/qdrant/pull/4578

**Comment by varshith257** [comment]
Thanks @generall

**Comment by varshith257** [comment]
@generall I had done this initial work long ago but lost track because of my exams and didn't; push changes here :( 
Recently two PRs were raised and came back here with this PR. If you feel my work is in the direction of issue solving, **a small tip** will be greatly appreciated for putting hours of effort into this issue and will keep me actively engaged in the community :)

**Comment by varshith257** [comment]
> @generall I had done this initial work long ago but lost track because of my exams and didn't; push changes here :( Recently two PRs were raised and came back here with this PR. If you feel my work is in the direction of issue solving, **a small tip** will be greatly appreciated for putting hours of effort into this issue and will keep me actively engaged in the community :)

@generall

**Pull request closed without merging**
