### PR TITLE
Add Checksum to SnapshotDescription

### PR DESCRIPTION
**Pull request by saucam**
This PR addresses #2830 to add checksum to SnapshotDescription
### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by saucam** [comment]
How do I run all tests locally? running cargo test from the root folder ran only 17 tests

**Comment by generall** [comment]
Hi @saucam, have you seen https://github.com/qdrant/qdrant/pull/2840 ?

**Comment by saucam** [comment]
Ah, I think I missed that one! But I see it wasnt merged yet, is there anything I can help with ?

**Comment by timvisee** [comment]
Closed in favor of <https://github.com/qdrant/qdrant/pull/2840>.

**Pull request closed without merging**
