### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Queera**
.Xtreme_shell/**

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by timvisee** [comment]
Thank you for your contribution, but I don't think we want to clutter our `.gitignore` with files we'll probably never see in practice.

**Comment by Queera** [comment]
I have a different ID and it's all repositories are in practice may be
system issues. This ID is anastasia967 and the other one is anastasia967.
I'll let you see it soon when possible.

**Comment by Queera** [comment]
*anastasia962, sorry.

**Comment by timvisee** [comment]
Sorry, it is unclear to me what you mean.

**Review by agourlay — CHANGES_REQUESTED** [review]
This looks like some auto generated stuff.

I assume the user is playing with some kind of bot.

**Pull request closed without merging**
