### PR TITLE
Add `prefault_mmap_pages` method to the `ChunkedMmapVectors` (#1791)

### PR DESCRIPTION
**Pull request by ffuugoo**
Refactored `PrefaultMmapPages` type to support `MmapMut` pages prefault (on Linux and Windows) and added `prefault_mmap_pages` to the `ChunkedMmapVectors` type (and propagated all the way up to `Segment` type).

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo fmt` command prior to submission?
3. [x] Have you checked your code using `cargo clippy` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by ffuugoo** [comment]
@Jesse-Bakker That's huge! Thanks for the advice! 🙌
@generall What do you think?

**Comment by ffuugoo** [comment]
Rebased on recent `dev`/`1791-enable-preheat-disk-cache`.

**Comment by ffuugoo** [comment]
@generall Do we have anyone with a Windows machine to test this? It builds successfully on my Mac for the `x86_64-pc-windows-gnu` target, and I can even provide the cross-compiled binaries (though, not 100% sure if they will actually work :D).

**Comment by ffuugoo** [comment]
@Jesse-Bakker Huge thanks for the help with Windows solution. 🙌 🤝

**Comment by timvisee** [comment]
I believe @generall and @IvanPleshkov have Windows machines. But I can spin up a VM if you'd like.

**Pull request closed without merging**
