### PR TITLE
Removes method from abort shard transfer operation

### PR DESCRIPTION
**Pull request by RPallas92**
Tracked in: https://github.com/qdrant/qdrant/issues/3409

This PR adds a new `AbortShardTransfer` struct, to be used by the `AbortTransfer` operation.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change? - There is one, but the CI does not pass.

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by timvisee** [comment]
Hi @RPallas92, thank you for your effort on this!

Could you first make sure the tests on CI pass? This probably needs a reformat: `cargo +nightly fmt --all`

**Comment by RPallas92** [comment]
cc: @timvisee 

> Hi @RPallas92, thank you for your effort on this!
> 
> Could you first make sure the tests on CI pass? This probably needs a reformat: `cargo +nightly fmt --all`

Hi @timvisee, thanks for reviewing. Sure, I have updated the PR, but I don´t have permissions to re-run the checks.

**Comment by RPallas92** [comment]
> cc: @timvisee
> 
> > Hi @RPallas92, thank you for your effort on this!
> > Could you first make sure the tests on CI pass? This probably needs a reformat: `cargo +nightly fmt --all`
> 
> Hi @timvisee, thanks for reviewing. Sure, I have updated the PR, but I don´t have permissions to re-run the checks.

Should I reopen the PR to force running the checks?

**Comment by xzfc** [comment]
I reran the checks. It seems you also need to regenerate JSON/gRPC schemas by running `tools/generate_grpc_docs.sh` and `tools/generate_openapi_models.sh`.

**Comment by RPallas92** [comment]
Closed in favor of https://github.com/qdrant/qdrant/pull/3803

**Pull request closed without merging**
