### PR TITLE
Create snapshots path of collection upon trigger of snapshot api

### PR DESCRIPTION
**Pull request by gulshan-rs**
### All Submissions:

Fixes: https://github.com/qdrant/qdrant/issues/5558 

We delay the snapshots path creation (directories and path) when the snapshot api is invoked. We however derive the snapshot path early in the collection creation flow to store a reference of it to be used across other collection API such as listing collection, shard snapshot transfer etc. 

Listing a collection snapshot in absence of the  snapshot path still works since [absence of a directory is returned as an OK of empty Vec](https://github.com/qdrant/qdrant/blob/dev/lib/collection/src/common/snapshots_manager.rs#L241) (which makes sense).

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Review by timvisee — APPROVED** [review]

**Review by timvisee — APPROVED** [review]
Thank you!

I added a commit on your branch to satisfy the linter.

**Review by ffuugoo — APPROVED** [review]

**Comment by gulshan-rs** [comment]
thanks @timvisee!

**Review by timvisee — CHANGES_REQUESTED** [review]
Judging by this CI run there's a bit more to be handled :smile: 

https://github.com/qdrant/qdrant/actions/runs/12143054864/job/33858987882?pr=5574

**Comment by gulshan-rs** [comment]
looking...

**Comment by gulshan-rs** [comment]
also made similar changes in ```/toc/mod.rs``` . Now, i think the problem may be within the test.

**Comment by gulshan-rs** [comment]
I'll setup my local integration test environment and try to figure out what's going wrong here. Will keep the issue open until then.

**Comment by timvisee** [comment]
The CI tests that are still failing are related to the changes here.

You should be able to run them locally with: `pytest -p no:cacheprovider ./tests/consensus_tests/test_snapshot_recovery.py`

**Comment by gulshan-rs** [comment]
ready for review.

**Review by timvisee — APPROVED** [review]
Thank you!

**Comment by gulshan-rs** [comment]
checking if this can be merged?

**Comment by timvisee** [comment]
It can. Thanks! :pray:

**Pull request merged**
