### PR TITLE
Enable raft message batching (#1519)

### PR DESCRIPTION
**Pull request by ffuugoo**
This PR enables built-in raft message batching. (See #1519.)

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by agourlay** [comment]
Could you elaborate a bit on the observable effects of this change? :chart_with_upwards_trend:

**Comment by timvisee** [comment]
> The only possible concern would be to check if we have any limit on maximal size of a single gRPC message, maybe we should increase it.

I thought we didn't have a limit on the internal API, but we should confirm it.

**Comment by ffuugoo** [comment]
> > The only possible concern would be to check if we have any limit on maximal size of a single gRPC message, maybe we should increase it.
> 
> I thought we didn't have a limit on the internal API, but we should confirm it.

Seems like [we don't](https://github.com/qdrant/qdrant/blob/9292dedb5c075231d99680d1ed27e91d2d18dc89/src/tonic/mod.rs#L345).

**Review by agourlay — APPROVED** [review]

**Review by timvisee — APPROVED** [review]

**Review by generall — APPROVED** [review]
I don't think would I have any insights without giving it a run on CI & chaos

**Pull request merged**
